export const SEARCH_REPOSITORIES = 'SEARCH_REPOSITORIES';
export const CLEAR_REPOSITORIES = 'CLEAR_REPOSITORIES';
export const SAVED_REPOSITORIES = 'SAVED_REPOSITORIES';
export const GET_REPOS = 'GET_REPOS';
export const SET_LOADING = 'SET_LOADING';
export const DELETE_REPOSITORIES = 'DELETE_REPOSITORIES';
